# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnHeat = QtWidgets.QPushButton(self.centralwidget)
        self.btnHeat.setGeometry(QtCore.QRect(40, 190, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btnHeat.setFont(font)
        self.btnHeat.setObjectName("btnHeat")
        self.labHeat = QtWidgets.QLabel(self.centralwidget)
        self.labHeat.setGeometry(QtCore.QRect(20, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labHeat.setFont(font)
        self.labHeat.setTextFormat(QtCore.Qt.AutoText)
        self.labHeat.setAlignment(QtCore.Qt.AlignCenter)
        self.labHeat.setObjectName("labHeat")
        self.labLamp1 = QtWidgets.QLabel(self.centralwidget)
        self.labLamp1.setGeometry(QtCore.QRect(190, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labLamp1.setFont(font)
        self.labLamp1.setTextFormat(QtCore.Qt.AutoText)
        self.labLamp1.setAlignment(QtCore.Qt.AlignCenter)
        self.labLamp1.setObjectName("labLamp1")
        self.btnLamp1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnLamp1.setGeometry(QtCore.QRect(210, 190, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btnLamp1.setFont(font)
        self.btnLamp1.setObjectName("btnLamp1")
        self.btnLamp2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnLamp2.setGeometry(QtCore.QRect(360, 190, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btnLamp2.setFont(font)
        self.btnLamp2.setObjectName("btnLamp2")
        self.labLamp2 = QtWidgets.QLabel(self.centralwidget)
        self.labLamp2.setGeometry(QtCore.QRect(340, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labLamp2.setFont(font)
        self.labLamp2.setTextFormat(QtCore.Qt.AutoText)
        self.labLamp2.setAlignment(QtCore.Qt.AlignCenter)
        self.labLamp2.setObjectName("labLamp2")
        self.btnLamp3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnLamp3.setGeometry(QtCore.QRect(520, 190, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btnLamp3.setFont(font)
        self.btnLamp3.setObjectName("btnLamp3")
        self.labLamp3 = QtWidgets.QLabel(self.centralwidget)
        self.labLamp3.setGeometry(QtCore.QRect(500, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labLamp3.setFont(font)
        self.labLamp3.setTextFormat(QtCore.Qt.AutoText)
        self.labLamp3.setAlignment(QtCore.Qt.AlignCenter)
        self.labLamp3.setObjectName("labLamp3")
        self.labLamp4 = QtWidgets.QLabel(self.centralwidget)
        self.labLamp4.setGeometry(QtCore.QRect(650, 100, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labLamp4.setFont(font)
        self.labLamp4.setTextFormat(QtCore.Qt.AutoText)
        self.labLamp4.setAlignment(QtCore.Qt.AlignCenter)
        self.labLamp4.setObjectName("labLamp4")
        self.btnLamp4 = QtWidgets.QPushButton(self.centralwidget)
        self.btnLamp4.setGeometry(QtCore.QRect(670, 190, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btnLamp4.setFont(font)
        self.btnLamp4.setObjectName("btnLamp4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TerraControl"))
        self.btnHeat.setText(_translate("MainWindow", "OFF"))
        self.labHeat.setText(_translate("MainWindow", "GRZANIE"))
        self.labLamp1.setText(_translate("MainWindow", "LAMPA 1"))
        self.btnLamp1.setText(_translate("MainWindow", "OFF"))
        self.btnLamp2.setText(_translate("MainWindow", "OFF"))
        self.labLamp2.setText(_translate("MainWindow", "LAMPA 2"))
        self.btnLamp3.setText(_translate("MainWindow", "OFF"))
        self.labLamp3.setText(_translate("MainWindow", "LAMPA 3"))
        self.labLamp4.setText(_translate("MainWindow", "LAMPA 4"))
        self.btnLamp4.setText(_translate("MainWindow", "OFF"))

